[package]
name = "geldparser"
version = "0.1.0"
authors = ["andreaskundig <andreas.kuendig@gmx.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mt940 = "0.3.2"
regex = "1.3.3"
lazy_static = "1.4.0"